version: 0.2

phases:
    pre_build:
        commands:
            - npm install
    build:
        commands:
            - npm run build

artifacts:
    base-directory: dist
    files:
        - '**/*'
cache:
    paths:
        - node_modules/**/*
